exclude: "venv|node_modules|.git"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
      - id: yesqa

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports

  # Don't work now because of https://github.com/FHPythonUtils/LicenseCheck/issues/17
  # - repo: https://github.com/FHPythonUtils/LicenseCheck
  #   rev: '2021.5'
  #   hooks:
  #     - id: licensecheck

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
        args: ["--recursive", "--exclude=tests,.venv"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2
    hooks:
      - id: python-safety-dependencies-check
        args: []

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
            pep8-naming,
            flake8-blind-except,
            flake8-bugbear,
            flake8-builtins,
            flake8-comprehensions,
            flake8-print,
            flake8-2020,
            flake8-requirements,
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
