exclude: ".venv|.git"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: end-of-file-fixer

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
        language_version: python3.10
        files: pyproject.toml

  - repo: https://github.com/python-poetry/poetry
    rev: "1.2"
    hooks:
      - id: poetry-check

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        language_version: python3.11

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: "v0.0.267"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3.11
        entry: flake8
        types: [python]
        require_serial: true
        args: ["--config=.flake8"]
        additional_dependencies:
          [
            flake8-mutable,
            flake8-noqa,
            flake8-warnings,
            flake8-class-attributes-order,
            flake8-functions-names,
            flake8-newspaper-style,
          ]
