version: "3.4"

services:
  auth-backend:
    container_name: auth-backend
    hostname: auth-backend
    build:
      context: ./
      dockerfile: src/docker/backend_Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
