version: "3.4"

services:
  docs-storage:
    hostname: docs-storage
    build:
      context: ./
      dockerfile: docker/backend_Dockerfile
    env_file:
      - env/dev/public.env
      - env/dev/.secret.env
    environment:
      - MONGO_HOST=mongo-db
    restart: unless-stopped
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    depends_on:
      - mongo-db

  mongo-db:
    hostname: mongo-db
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - env/dev/mongo.env
    volumes:
      - ./mongo_data:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
