import pathlib


class FileMetaController:

    def create_dir(self, name: str, *, path: pathlib.Path) -> pathlib.Path: ...

    def delete_dir(self, name: str, *, path: pathlib.Path) -> pathlib.Path: ...

    def rename_dir(self, *, old_name: str, new_name: str, path: pathlib.Path) -> pathlib.Path: ...

    def ls(self, *, path: pathlib.Path) -> list[pathlib.Path]: ...

    def parent(self, *, path: pathlib.Path) -> pathlib.Path: ...

    def child(self, *, name: str, path: pathlib.Path) -> pathlib.Path: ...
