name: Run tests on any Push event

on:
  push:
    branches:
      - "main"

jobs:
  run_pre_commit:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install requirements
        run: poetry install

      - name: Run linters and formatters
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  run_tests:
    runs-on: [ubuntu-latest]
    needs: [run_pre_commit]
    env:
      ENVIRONMENT: "prod"

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install requirements
        run: poetry install

      - name: create secret envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_CSRF_SECRET_TOKEN: ${{ secrets.CSRF_SECRET_TOKEN }}
          directory: env/${{env.ENVIRONMENT}}/
          file_name: .secret.env
          fail_on_empty: true

      - name: Run tests
        run: poetry run pytest

  deploy_to_dockerhub:
    runs-on: [ubuntu-latest]
    needs: [run_tests]

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: niccolum/docs-storage

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docs-storage:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/docs-storage:latest
