name: ci

on:
  push:
    branches:
      - "main"

jobs:
  run_pre_commit:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install requirements
        run: poetry install

      - name: Run linters and formatters
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

  run_tests:
    runs-on: [ubuntu-latest]
    needs: [run_pre_commit]
    env:
      ENVIRONMENT: "dev"

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pip install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install requirements
        run: poetry install

      - name: create secret envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_SECURITY_CSRF_SECRET_TOKEN: ${{ secrets.CSRF_SECRET_TOKEN }}
          directory: env/${{env.ENVIRONMENT}}/
          file_name: .secret.env
          fail_on_empty: true

      - name: Run tests
        run: poetry run pytest

  deploy_to_dockerhub:
    runs-on: [ubuntu-latest]
    needs: [run_tests]

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: niccolum
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create tag in github
        id: tags
        uses: phish108/autotag-action@v1.1.64
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}

      - name: Extract tags for Docker
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: niccolum/docs-storage
          tags: |
            type=pep440,pattern=v{{major}},enable={{is_default_branch}},value=${{ steps.tags.outputs.new-tag }}
            type=pep440,pattern={{version}},enable={{is_default_branch}},value=${{ steps.tags.outputs.new-tag }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: src/docker/backend_Dockerfile
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
